In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from bs4 import BeautifulSoup

import requests

import warnings
warnings.filterwarnings('ignore')

In [2]:
url = 'https://www.recenter.tamu.edu/data/housing-activity#!/activity/MSA/San_Antonio-New_Braunfels'

In [3]:
response = requests.get(url)
response

In [4]:
response.text

'\r\n<!DOCTYPE html >\n<html ng-app="userInterface" dir="ltr" class="ms-isBot" lang="en-US">\r\n    <head><meta http-equiv="X-UA-Compatible" content="IE=Edge" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta name="description" content="Real Estate Center at Texas A&amp;M University, helping Texans make better real estate decisions." /><meta property="og:image" content="https://www.recenter.tamu.edu/_catalogs/masterpage/REC/assets/images/rec-og-logo.jpg" /><meta name="GENERATOR" content="Microsoft SharePoint" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Expires" content="0" /><link rel="icon" type="image/png" href="/_catalogs/masterpage/REC/assets/images/favicon.ico" /><link rel="image_src" type="image/jpeg" href="/_catalogs/masterpage/REC/assets/images/rec-og-logo.jpg" />\r\n        <!--removeIf(local)-->\r\n        <title>\r\n\t\r\n            \r\n            \r\n            Housing Activity\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n - \r\n                                                                                                                                                                                                Real Estate Center\r\n            \r\n        \r\n</title><link rel="stylesheet" type="text/css" href="/_layouts/15/1033/styles/Themable/corev15.css?rev=f4ES4o33Y5B6OSnm1GOXLA%3D%3DTAG0"/>\n<script type="text/javascript" src="/_layouts/15/1033/initstrings.js?rev=2WxjgxyM2qXGgY9r2nHW8A%3D%3DTAG0"></script>\n<script type="text/javascript" src="/_layouts/15/init.js?rev=hxEMKTeQnCJMCWRbN0KepQ%3D%3DTAG0"></script>\n<script type="text/javascript" src="/ScriptResource.axd?d=rAaCHi21TOBTpHdp5f1mq1k5X-3qf66_yOPntKgXGisaNin_u1JVcNo3PSlEShWm6eF-hmDYf9UPfO4IdFXkaw6YCYhsWdhP7_iBvZ_a7WKXT4114OM3CTQtq_7Q4Lh3SL9-IrQ5NHwr065UTKvVg0iP2gT-NbAWLCU0Lp0V2s3aN1d918rKW68j7vRmU6Zl0&amp;t=ffffffffaa493ab8"></script>\n<script type="text/javascript" src="/_layouts/15/blank.js?rev=01HRKg2GvQ0OLPDOjRjeBw%3D%3DTAG0"></script>\n<script type="text/javascript">RegisterSod("require.js", "\\u002f_layouts\\u002f15\\u002frequire.js?rev=4UhLIF\\u00252FezOvmGnh\\u00252Fs0LLpA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("strings.js", "\\u002f_layouts\\u002f15\\u002f1033\\u002fstrings.js?rev=k\\u00252FSaOdWtcHDDvsb\\u00252FUFykOA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.res.resx", "\\u002f_layouts\\u002f15\\u002f1033\\u002fsp.res.js?rev=MbB92HT8biYuFa\\u00252B1vTMilA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.runtime.js", "\\u002f_layouts\\u002f15\\u002fsp.runtime.js?rev=5VzZER4J86QQUaVrFtXAgA\\u00253D\\u00253DTAG0");RegisterSodDep("sp.runtime.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("sp.js", "\\u002f_layouts\\u002f15\\u002fsp.js?rev=OhfPJyW7FuEWL7FcI5RzzQ\\u00253D\\u00253DTAG0");RegisterSodDep("sp.js", "sp.runtime.js");RegisterSodDep("sp.js", "sp.ui.dialog.js");RegisterSodDep("sp.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("sp.init.js", "\\u002f_layouts\\u002f15\\u002fsp.init.js?rev=US4aUhQP9KhuHKZiSjRv7g\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.ui.dialog.js", "\\u002f_layouts\\u002f15\\u002fsp.ui.dialog.js?rev=irNtBFKtwvTB\\u00252BTuuT0m0MQ\\u00253D\\u00253DTAG0");RegisterSodDep("sp.ui.dialog.js", "sp.init.js");RegisterSodDep("sp.ui.dialog.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("core.js", "\\u002f_layouts\\u002f15\\u002fcore.js?rev=THwNeN3FEGkc\\u00252B1Nykq9TRQ\\u00253D\\u00253DTAG0");RegisterSodDep("core.js", "strings.js");</script>\n<script type="text/javascript">RegisterSod("menu.js", "\\u002f_layouts\\u002f15\\u002fmenu.js?rev=cVNqbVcV\\u00252Fod6FTtn2DG2\\u00252Fg\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("mQuery.js", "\\u002f_layouts\\u002f15\\u002fmquery.js?rev=x0ZFhEs6FU9DZstmK1PAwQ\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("callout.js", "\\u002f_layouts\\u002f15\\u002fcallout.js?rev=fDE2RyFe548yUgKrv7rf6g\\u00253D\\u00253DTAG0");RegisterSodDep("callout.js", "strings.js");RegisterSodDep("callout.js", "mQuery.js");RegisterSodDep("callout.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("sp.core.js", "\\u002f_layouts\\u002f15\\u002fsp.core.js?rev=C3z0TGLqbvmxR5DXuqfM1g\\u00253D\\u00253DTAG0");RegisterSodDep("sp.core.js", "strings.js");RegisterSodDep("sp.core.js", "sp.init.js");RegisterSodDep("sp.core.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("sharedhovercard.strings.js", "\\u002f_layouts\\u002f15\\u002f1033\\u002fsharedhovercard.strings.js?rev=sLsS\\u00252FNPqFzOSO42e3s6lgw\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sharedhovercard.js", "\\u002f_layouts\\u002f15\\u002fsharedhovercard.js?rev=uB89up9szoXj8bAMKPkPSg\\u00253D\\u00253DTAG0");RegisterSodDep("sharedhovercard.js", "sharedhovercard.strings.js");</script>\n<script type="text/javascript">RegisterSod("clienttemplates.js", "\\u002f_layouts\\u002f15\\u002fclienttemplates.js?rev=d6KwpUIem6DaOnA7yRq6zw\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sharing.js", "\\u002f_layouts\\u002f15\\u002fsharing.js?rev=\\u00252Fv0q3sUWnGYIUAAH4xsmCQ\\u00253D\\u00253DTAG0");RegisterSodDep("sharing.js", "strings.js");RegisterSodDep("sharing.js", "mQuery.js");RegisterSodDep("sharing.js", "clienttemplates.js");RegisterSodDep("sharing.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("suitelinks.js", "\\u002f_layouts\\u002f15\\u002fsuitelinks.js?rev=ic2tMBzPY3Jh\\u00252F6B\\u00252BldHo6Q\\u00253D\\u00253DTAG0");RegisterSodDep("suitelinks.js", "strings.js");RegisterSodDep("suitelinks.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("browserScript", "\\u002f_layouts\\u002f15\\u002fnon_ie.js?rev=knjuZk2rXIM3XhqUOTiSlg\\u00253D\\u00253DTAG0");RegisterSodDep("browserScript", "strings.js");</script>\n<script type="text/javascript">RegisterSod("inplview", "\\u002f_layouts\\u002f15\\u002finplview.js?rev=0yxxrO78LFSJff5VK02pnA\\u00253D\\u00253DTAG0");RegisterSodDep("inplview", "strings.js");RegisterSodDep("inplview", "core.js");RegisterSodDep("inplview", "clienttemplates.js");RegisterSodDep("inplview", "sp.js");</script>\n<link type="text/xml" rel="alternate" href="/_vti_bin/spsdisco.aspx" />\r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n        \r\n            <link rel="canonical" href="https://www.recenter.tamu.edu:443/data/housing-activity" />\r\n            \r\n            \r\n        <span id="DeltaSPWebPartManager">\r\n        \r\n        </span>\r\n        \r\n        \r\n        <!--endRemoveIf(local)-->\r\n        <link rel="stylesheet" href="/_catalogs/masterpage/REC/styles/vendor.css" /><link rel="stylesheet" href="/_catalogs/masterpage/REC/styles/app.css" /></head>\r\n    <body onhashchange="if (typeof(_spBodyOnHashChange) != \'undefined\') _spBodyOnHashChange();"><div id="imgPrefetch" style="display:none">\r\n<img src="/_layouts/15/images/spcommon.png?rev=40" />\r\n</div>\r\n<form method="post" action="./housing-activity?TermStoreId=b9ff756e-1720-40ce-a1cf-38d0ec67f7e2&amp;TermSetId=24866657-2b8c-4d52-af66-1944622c9be8&amp;TermId=9df2a16f-c28f-497f-984a-6d53241980c1" id="aspnetForm">\r\n<input type="hidden" name="_wpcmWpid" id="_wpcmWpid" value="" />\r\n<input type="hidden" name="wpcmVal" id="wpcmVal" value="" />\r\n<input type="hidden" name="MSOWebPartPage_PostbackSource" id="MSOWebPartPage_PostbackSource" value="" />\r\n<input type="hidden" name="MSOTlPn_SelectedWpId" id="MSOTlPn_SelectedWpId" value="" />\r\n<input type="hidden" name="MSOTlPn_View" id="MSOTlPn_View" value="0" />\r\n<input type="hidden" name="MSOTlPn_ShowSettings" id="MSOTlPn_ShowSettings" value="False" />\r\n<input type="hidden" name="MSOGallery_SelectedLibrary" id="MSOGallery_SelectedLibrary" value="" />\r\n<input type="hidden" name="MSOGallery_FilterString" id="MSOGallery_FilterString" value="" />\r\n<input type="hidden" name="MSOTlPn_Button" id="MSOTlPn_Button" value="none" />\r\n<input type="hidden" name="__REQUESTDIGEST" id="__REQUESTDIGEST" value="noDigest" />\r\n<input type="hidden" name="MSOSPWebPartManager_DisplayModeName" id="MSOSPWebPartManager_DisplayModeName" value="Browse" />\r\n<input type="hidden" name="MSOSPWebPartManager_ExitingDesignMode" id="MSOSPWebPartManager_ExitingDesignMode" value="false" />\r\n<input type="hidden" name="MSOWebPartPage_Shared" id="MSOWebPartPage_Shared" value="" />\r\n<input type="hidden" name="MSOLayout_LayoutChanges" id="MSOLayout_LayoutChanges" value="" />\r\n<input type="hidden" name="MSOLayout_InDesignMode" id="MSOLayout_InDesignMode" value="" />\r\n<input type="hidden" name="_wpSelected" id="_wpSelected" value="" />\r\n<input type="hidden" name="_wzSelected" id="_wzSelected" value="" />\r\n<input type="hidden" name="MSOSPWebPartManager_OldDisplayModeName" id="MSOSPWebPartManager_OldDisplayModeName" value="Browse" />\r\n<input type="hidden" name="MSOSPWebPartManager_StartWebPartEditingName" id="MSOSPWebPartManager_StartWebPartEditingName" value="false" />\r\n<input type="hidden" name="MSOSPWebPartManager_EndWebPartEditing" id="MSOSPWebPartManager_EndWebPartEditing" value="false" />\r\n<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUBMA9kFgJmD2QWAgIBD2QWBAIBD2QWBgILD2QWAmYPZBYCAgEPFgIeE1ByZXZpb3VzQ29udHJvbE1vZGULKYgBTWljcm9zb2Z0LlNoYXJlUG9pbnQuV2ViQ29udHJvbHMuU1BDb250cm9sTW9kZSwgTWljcm9zb2Z0LlNoYXJlUG9pbnQsIFZlcnNpb249MTYuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49NzFlOWJjZTExMWU5NDI5YwFkAhcPZBYCAgMPZBYCZg9kFgJmDzwrAAYAZAIZD2QWAgIBD2QWAgUmZ18xNDU1Zjk2Ml9jMmM0XzQyZWNfOThkMF82N2EwZTY4YWY4ZTkPZBYEZg8WAh4HVmlzaWJsZWhkAgEPFgIfAWhkAgUPZBYCAgYPZBYCAgIPZBYCAgEPZBYCAgMPFgIfAWgWAmYPZBYEAgMPZBYEAgEPFgIfAWhkAgMPFgIfAWhkAgQPDxYCHglBY2Nlc3NLZXkFAS9kZGSaZRH2aTDLltNDQH3Cy5+Ff7A6OOWjYicXosYqkTRZRg==" />\r\n\r\n\r\n<script type="text/javascript">\r\n//<![CDATA[\r\nvar MSOWebPartPageFormName = \'aspnetForm\';\nvar g_presenceEnabled = true;\nvar g_wsaEnabled = false;\n\nvar g_correlationId = \'97f0b3a0-d9db-6077-d874-82596e99142a\';\nvar g_wsaQoSEnabled = false;\nvar g_wsaQoSDataPoints = [];\nvar g_wsaRUMEnabled = false;\nvar g_wsaLCID = 1033;\nvar g_wsaListTemplateId = 850;\nvar g_wsaSiteTemplateId = \'STS#0\';\nvar _fV4UI=true;var _spPageContextInfo = {webServerRelativeUrl: "\\u002f", webAbsoluteUrl: "https:\\u002f\\u002fwww.recenter.tamu.edu", siteAbsoluteUrl: "https:\\u002f\\u002fwww.recenter.tamu.edu", serverRequestPath: "\\u002fPages\\u002fhousing-activity.aspx", layoutsUrl: "_layouts\\u002f15", webTitle: "Real Estate Center", webTemplate: "1", tenantAppVersion: "0", isAppWeb: false, Has2019Era: true, webLogoUrl: "_layouts\\u002f15\\u002fimages\\u002fsiteicon.png", webLanguage: 1033, currentLanguage: 1033, currentUICultureName: "en-US", currentCultureName: "en-US", clientServerTimeDelta: new Date("2023-05-18T03:17:17.9170389Z") - new Date(), updateFormDigestPageLoaded: new Date("2023-05-18T03:17:17.9170389Z"), siteClientTag: "2906$$16.0.5056.1001", crossDomainPhotosEnabled:false, webUIVersion:15, webPermMasks:{High:16,Low:196673},pageListId:"{377a456c-c72a-435b-8851-384c6bfc543e}",pageItemId:13, pagePersonalizationScope:1, alertsEnabled:true, siteServerRelativeUrl: "\\u002f", allowSilverlightPrompt:\'True\', isSiteAdmin: false};document.onreadystatechange=fnRemoveAllStatus; function fnRemoveAllStatus(){removeAllStatus(true)};Flighting.ExpFeatures = [480215056,1880287568,1561350208,302071836,3212816,69472768,4194310,-2113396707,268502022,-872284160,1049232,-2147421952,65536,65536,2097472,917504,-2147474174,1372324107,67108882,0,0,-2147483648,2097152,0,0,32768,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32768];var _spWebPartComponents = new Object();//]]>\r\n</script>\r\n\r\n<script src="/_layouts/15/blank.js?rev=01HRKg2GvQ0OLPDOjRjeBw%3D%3DTAG0" type="text/javascript"></script>\r\n<script type="text/javascript">\r\n//<![CDATA[\r\nif (typeof(DeferWebFormInitCallback) == \'function\') DeferWebFormInitCallback();//]]>\r\n</script>\r\n\r\n<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="BF82A2A0" />\r\n        <!--removeIf(local)-->\r\n        <div id="ms-designer-ribbon">\r\n            \r\n            <div id="TurnOnAccessibility" style="display:none" class="s4-notdlg noindex">\r\n                <a id="linkTurnOnAcc" href="#" class="ms-accessible ms-acc-button" onclick="SetIsAccessibilityFeatureEnabled(true);UpdateAccessibilityUI();document.getElementById(\'linkTurnOffAcc\').focus();return false;">\r\n                    Turn on more accessible mode\r\n                </a>\r\n            </div>\r\n            <div id="TurnOffAccessibility" style="display:none" class="s4-notdlg noindex">\r\n                <a id="linkTurnOffAcc" href="#" class="ms-accessible ms-acc-button" onclick="SetIsAccessibilityFeatureEnabled(false);UpdateAccessibilityUI();document.getElementById(\'linkTurnOnAcc\').focus();return false;">\r\n                    Turn off more accessible mode\r\n                </a>\r\n            </div>\r\n            <div>\r\n\t\r\n\t<div id="s4-ribbonrow" style="visibility:hidden;display:none"></div>\r\n\r\n</div>\r\n\r\n\r\n            \r\n        </div>\r\n        <!--endRemoveIf(local)-->\r\n        <div id="s4-workspace" class="s4-nosetwidth">\r\n            <div id="s4-bodyContainer" ng-controller="MainCtrl" ng-cloak="">\r\n                <div ng-include="\'app/components/navbar/navbar.html\'"></div>\r\n                <div class="rec-banner">\r\n                    <a ng-href="{{banner.link}}">\r\n                        <img ng-src="{{banner.source}}" ng-if="banner.source" />\r\n                    </a>\r\n                </div>\r\n                <div class="container">\r\n                    <h1 ng-if="titleBar.title" class="page-header">{{titleBar.title}}</h1>\r\n                    <p ng-if="titleBar.tagline" class="tagline">{{titleBar.tagline}}</p>\r\n                    <div>\r\n                        \r\n                        \r\n                        <span id="DeltaPlaceHolderMain">\r\n                            \r\n            <div>\r\n                \r\n                \r\n                \r\n                \r\n                \r\n            </div>\r\n            <div class="row">\r\n                <div class="col-xs-12">\r\n                    <div data-name="WebPartZone">\r\n                        \r\n                        \r\n                        <div>\r\n                            <div class="ms-webpart-zone ms-fullWidth">\r\n\t<div id="MSOZoneCell_WebPartWPQ1" class="s4-wpcell-plain ms-webpartzone-cell ms-webpart-cell-vertical ms-fullWidth ">\r\n\t\t<div class="ms-webpart-chrome ms-webpart-chrome-vertical ms-webpart-chrome-fullWidth ">\r\n\t\t\t<div WebPartID="1455f962-c2c4-42ec-98d0-67a0e68af8e9" HasPers="false" id="WebPartWPQ1" width="100%" class="ms-WPBody noindex " allowDelete="false" style="" ><div class="ms-rtestate-field"><div class="row building-data data-page" ng-controller="HousingDataCtrl" ng-cloak="">\n    <update-meta name="description" content="Housing statistics are based on listing data from over 50 MLS (Multiple Listing Service) systems in Texas. Statistics for each geography were calculated based on listings of properties physically located within the mapped area presented with the statistics."></update-meta>\n    <div class="col-xs-12 col-sm-8" ng-if="!selected.view">\n        <div ng-if="oldDataIsAvailable && !oldData">\n            <h1>Housing Activity &amp; Affordability</h1>\n            <p>Residential home sales, listings, price activity and affordability for nearly 50 Texas metropolitan MLS (Multiple Listing Service) areas.</p>\n            <h4>About the Data</h4>\n            <p>\n                Data used in Housing Activity comes from the Texas REALTOR&reg; Data Relevance Project, a partnership among local REALTOR&reg; associations and their MLSs, the Texas Real Estate Research Center at Texas A&M University, and the Texas Association of REALTORS&reg;.\n                The Data Relevance Project data series differs from the Discontinued Housing Activity data series in two ways:\n            </p>\n            <ol>\n                <li>Includes data from more MLS systems in Texas.</li>\n                <li>A deduplication process has been implemented to remove duplicate listings for a single property.</li>\n            </ol>\n            <p>This process eliminates the impact of properties that have been listed multiple times within an MLS system or across multiple MLS systems.</p>\n        </div>\n        <div ng-if="oldDataIsAvailable && oldData">\n            <h3>Housing Activity &amp; Affordability (Discontinued)</h3>\n            <p>Residential home sales, listings, price activity and affordability for nearly 50 Texas metropolitan MLS (Multiple Listing Service) areas.</p>\n            <h4>About the Data</h4>\n            <p>\n                Data in this Discontinued series was independently reported to the Texas Real Estate Research Center by MLS systems across Texas. As of December 2015 this reporting process has been replaced by MLS system reporting through the Texas REALTOR® Data Relevance Project. The Center has retired this data series and will no longer make updates to it.\n            </p>\n        </div>\n        <div ng-if="!oldDataIsAvailable">\n            <h1>Housing Activity</h1>\n            <h4>Data Series Description</h4>\n            <p>\n                Housing statistics are based on listing data from over 50 MLS (Multiple Listing Service) systems in Texas. Statistics for each geography were calculated based on listings of properties physically located within the mapped area presented with the statistics.\n            </p>\n            <h4>Geographic Definitions</h4>\n            <p>\n                Metropolitan Statistical Area (MSA): Based on the multi-county area specified by The Office of Management & Budget in 2013.\n            </p>\n            <p>\n                Local Market Area (LMA): An area defined by the local Association/Board of REALTORS representing a logical market of homes that can be grouped together for meaningful statistical reporting.\n            </p>\n            <h4>Getting More Detail</h4>\n            <p>\n                For more detailed statistics about local areas, existing vs. new homes and breakout by property type, contact your local REALTOR&reg; association. <a href ="https://www.texasrealestate.com/about-us/local-associations/alphabetical-list/" target="_blank">Click here</a> for a list of contacts.\n            </p>\n            <h4>Data Release Dates</h4>\n            <p>\n                Statistics for geographies outside of the Houston metro area will be released on/near the 20th calendar day after month end. Statistics for the Houston metro area will be released on/near the 40th calendar day after month end.\n            </p>            \n        </div>\n    </div>\n    <div class="col-xs-12 col-sm-8" ng-show="data && selected.view == \'trends\'" ng-controller="HousingTrendsCtrl">\n        <h1>Housing Activity Trends</h1>\n        <update-title ng-if="selected.view == \'trends\'" title="Housing Activity Trends - Texas Real Estate Research Center"></update-title>\n        <tabset>\n            <tab ng-repeat="trend in trendTypes" heading="{{trend.name}}" select="selectTrendType(trend)">\n                \n            </tab>\n        </tabset>\n        <highchart config="trendChartConfig"></highchart>\n        <table class="table table-bordered table-hover table-condensed rec-table fix-chrome-copy-bug">\n            <thead>\n                <tr>\n                     <th rowspan="2">MLS Area</th>\n   

In [5]:
response.content

b'\r\n<!DOCTYPE html >\n<html ng-app="userInterface" dir="ltr" class="ms-isBot" lang="en-US">\r\n    <head><meta http-equiv="X-UA-Compatible" content="IE=Edge" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta name="description" content="Real Estate Center at Texas A&amp;M University, helping Texans make better real estate decisions." /><meta property="og:image" content="https://www.recenter.tamu.edu/_catalogs/masterpage/REC/assets/images/rec-og-logo.jpg" /><meta name="GENERATOR" content="Microsoft SharePoint" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Expires" content="0" /><link rel="icon" type="image/png" href="/_catalogs/masterpage/REC/assets/images/favicon.ico" /><link rel="image_src" type="image/jpeg" href="/_catalogs/masterpage/REC/assets/images/rec-og-logo.jpg" />\r\n        <!--removeIf(local)-->\r\n        <title>\r\n\t\r\n            \r\n            \r\n            Housing Activity\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n - \r\n                                                                                                                                                                                                Real Estate Center\r\n            \r\n        \r\n</title><link rel="stylesheet" type="text/css" href="/_layouts/15/1033/styles/Themable/corev15.css?rev=f4ES4o33Y5B6OSnm1GOXLA%3D%3DTAG0"/>\n<script type="text/javascript" src="/_layouts/15/1033/initstrings.js?rev=2WxjgxyM2qXGgY9r2nHW8A%3D%3DTAG0"></script>\n<script type="text/javascript" src="/_layouts/15/init.js?rev=hxEMKTeQnCJMCWRbN0KepQ%3D%3DTAG0"></script>\n<script type="text/javascript" src="/ScriptResource.axd?d=rAaCHi21TOBTpHdp5f1mq1k5X-3qf66_yOPntKgXGisaNin_u1JVcNo3PSlEShWm6eF-hmDYf9UPfO4IdFXkaw6YCYhsWdhP7_iBvZ_a7WKXT4114OM3CTQtq_7Q4Lh3SL9-IrQ5NHwr065UTKvVg0iP2gT-NbAWLCU0Lp0V2s3aN1d918rKW68j7vRmU6Zl0&amp;t=ffffffffaa493ab8"></script>\n<script type="text/javascript" src="/_layouts/15/blank.js?rev=01HRKg2GvQ0OLPDOjRjeBw%3D%3DTAG0"></script>\n<script type="text/javascript">RegisterSod("require.js", "\\u002f_layouts\\u002f15\\u002frequire.js?rev=4UhLIF\\u00252FezOvmGnh\\u00252Fs0LLpA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("strings.js", "\\u002f_layouts\\u002f15\\u002f1033\\u002fstrings.js?rev=k\\u00252FSaOdWtcHDDvsb\\u00252FUFykOA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.res.resx", "\\u002f_layouts\\u002f15\\u002f1033\\u002fsp.res.js?rev=MbB92HT8biYuFa\\u00252B1vTMilA\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.runtime.js", "\\u002f_layouts\\u002f15\\u002fsp.runtime.js?rev=5VzZER4J86QQUaVrFtXAgA\\u00253D\\u00253DTAG0");RegisterSodDep("sp.runtime.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("sp.js", "\\u002f_layouts\\u002f15\\u002fsp.js?rev=OhfPJyW7FuEWL7FcI5RzzQ\\u00253D\\u00253DTAG0");RegisterSodDep("sp.js", "sp.runtime.js");RegisterSodDep("sp.js", "sp.ui.dialog.js");RegisterSodDep("sp.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("sp.init.js", "\\u002f_layouts\\u002f15\\u002fsp.init.js?rev=US4aUhQP9KhuHKZiSjRv7g\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sp.ui.dialog.js", "\\u002f_layouts\\u002f15\\u002fsp.ui.dialog.js?rev=irNtBFKtwvTB\\u00252BTuuT0m0MQ\\u00253D\\u00253DTAG0");RegisterSodDep("sp.ui.dialog.js", "sp.init.js");RegisterSodDep("sp.ui.dialog.js", "sp.res.resx");</script>\n<script type="text/javascript">RegisterSod("core.js", "\\u002f_layouts\\u002f15\\u002fcore.js?rev=THwNeN3FEGkc\\u00252B1Nykq9TRQ\\u00253D\\u00253DTAG0");RegisterSodDep("core.js", "strings.js");</script>\n<script type="text/javascript">RegisterSod("menu.js", "\\u002f_layouts\\u002f15\\u002fmenu.js?rev=cVNqbVcV\\u00252Fod6FTtn2DG2\\u00252Fg\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("mQuery.js", "\\u002f_layouts\\u002f15\\u002fmquery.js?rev=x0ZFhEs6FU9DZstmK1PAwQ\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("callout.js", "\\u002f_layouts\\u002f15\\u002fcallout.js?rev=fDE2RyFe548yUgKrv7rf6g\\u00253D\\u00253DTAG0");RegisterSodDep("callout.js", "strings.js");RegisterSodDep("callout.js", "mQuery.js");RegisterSodDep("callout.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("sp.core.js", "\\u002f_layouts\\u002f15\\u002fsp.core.js?rev=C3z0TGLqbvmxR5DXuqfM1g\\u00253D\\u00253DTAG0");RegisterSodDep("sp.core.js", "strings.js");RegisterSodDep("sp.core.js", "sp.init.js");RegisterSodDep("sp.core.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("sharedhovercard.strings.js", "\\u002f_layouts\\u002f15\\u002f1033\\u002fsharedhovercard.strings.js?rev=sLsS\\u00252FNPqFzOSO42e3s6lgw\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sharedhovercard.js", "\\u002f_layouts\\u002f15\\u002fsharedhovercard.js?rev=uB89up9szoXj8bAMKPkPSg\\u00253D\\u00253DTAG0");RegisterSodDep("sharedhovercard.js", "sharedhovercard.strings.js");</script>\n<script type="text/javascript">RegisterSod("clienttemplates.js", "\\u002f_layouts\\u002f15\\u002fclienttemplates.js?rev=d6KwpUIem6DaOnA7yRq6zw\\u00253D\\u00253DTAG0");</script>\n<script type="text/javascript">RegisterSod("sharing.js", "\\u002f_layouts\\u002f15\\u002fsharing.js?rev=\\u00252Fv0q3sUWnGYIUAAH4xsmCQ\\u00253D\\u00253DTAG0");RegisterSodDep("sharing.js", "strings.js");RegisterSodDep("sharing.js", "mQuery.js");RegisterSodDep("sharing.js", "clienttemplates.js");RegisterSodDep("sharing.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("suitelinks.js", "\\u002f_layouts\\u002f15\\u002fsuitelinks.js?rev=ic2tMBzPY3Jh\\u00252F6B\\u00252BldHo6Q\\u00253D\\u00253DTAG0");RegisterSodDep("suitelinks.js", "strings.js");RegisterSodDep("suitelinks.js", "core.js");</script>\n<script type="text/javascript">RegisterSod("browserScript", "\\u002f_layouts\\u002f15\\u002fnon_ie.js?rev=knjuZk2rXIM3XhqUOTiSlg\\u00253D\\u00253DTAG0");RegisterSodDep("browserScript", "strings.js");</script>\n<script type="text/javascript">RegisterSod("inplview", "\\u002f_layouts\\u002f15\\u002finplview.js?rev=0yxxrO78LFSJff5VK02pnA\\u00253D\\u00253DTAG0");RegisterSodDep("inplview", "strings.js");RegisterSodDep("inplview", "core.js");RegisterSodDep("inplview", "clienttemplates.js");RegisterSodDep("inplview", "sp.js");</script>\n<link type="text/xml" rel="alternate" href="/_vti_bin/spsdisco.aspx" />\r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n        \r\n            <link rel="canonical" href="https://www.recenter.tamu.edu:443/data/housing-activity" />\r\n            \r\n            \r\n        <span id="DeltaSPWebPartManager">\r\n        \r\n        </span>\r\n        \r\n        \r\n        <!--endRemoveIf(local)-->\r\n        <link rel="stylesheet" href="/_catalogs/masterpage/REC/styles/vendor.css" /><link rel="stylesheet" href="/_catalogs/masterpage/REC/styles/app.css" /></head>\r\n    <body onhashchange="if (typeof(_spBodyOnHashChange) != \'undefined\') _spBodyOnHashChange();"><div id="imgPrefetch" style="display:none">\r\n<img src="/_layouts/15/images/spcommon.png?rev=40" />\r\n</div>\r\n<form method="post" action="./housing-activity?TermStoreId=b9ff756e-1720-40ce-a1cf-38d0ec67f7e2&amp;TermSetId=24866657-2b8c-4d52-af66-1944622c9be8&amp;TermId=9df2a16f-c28f-497f-984a-6d53241980c1" id="aspnetForm">\r\n<input type="hidden" name="_wpcmWpid" id="_wpcmWpid" value="" />\r\n<input type="hidden" name="wpcmVal" id="wpcmVal" value="" />\r\n<input type="hidden" name="MSOWebPartPage_PostbackSource" id="MSOWebPartPage_PostbackSource" value="" />\r\n<input type="hidden" name="MSOTlPn_SelectedWpId" id="MSOTlPn_SelectedWpId" value="" />\r\n<input type="hidden" name="MSOTlPn_View" id="MSOTlPn_View" value="0" />\r\n<input type="hidden" name="MSOTlPn_ShowSettings" id="MSOTlPn_ShowSettings" value="False" />\r\n<input type="hidden" name="MSOGallery_SelectedLibrary" id="MSOGallery_SelectedLibrary" value="" />\r\n<input type="hidden" name="MSOGallery_FilterString" id="MSOGallery_FilterString" value="" />\r\n<input type="hidden" name="MSOTlPn_Button" id="MSOTlPn_Button" value="none" />\r\n<input type="hidden" name="__REQUESTDIGEST" id="__REQUESTDIGEST" value="noDigest" />\r\n<input type="hidden" name="MSOSPWebPartManager_DisplayModeName" id="MSOSPWebPartManager_DisplayModeName" value="Browse" />\r\n<input type="hidden" name="MSOSPWebPartManager_ExitingDesignMode" id="MSOSPWebPartManager_ExitingDesignMode" value="false" />\r\n<input type="hidden" name="MSOWebPartPage_Shared" id="MSOWebPartPage_Shared" value="" />\r\n<input type="hidden" name="MSOLayout_LayoutChanges" id="MSOLayout_LayoutChanges" value="" />\r\n<input type="hidden" name="MSOLayout_InDesignMode" id="MSOLayout_InDesignMode" value="" />\r\n<input type="hidden" name="_wpSelected" id="_wpSelected" value="" />\r\n<input type="hidden" name="_wzSelected" id="_wzSelected" value="" />\r\n<input type="hidden" name="MSOSPWebPartManager_OldDisplayModeName" id="MSOSPWebPartManager_OldDisplayModeName" value="Browse" />\r\n<input type="hidden" name="MSOSPWebPartManager_StartWebPartEditingName" id="MSOSPWebPartManager_StartWebPartEditingName" value="false" />\r\n<input type="hidden" name="MSOSPWebPartManager_EndWebPartEditing" id="MSOSPWebPartManager_EndWebPartEditing" value="false" />\r\n<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUBMA9kFgJmD2QWAgIBD2QWBAIBD2QWBgILD2QWAmYPZBYCAgEPFgIeE1ByZXZpb3VzQ29udHJvbE1vZGULKYgBTWljcm9zb2Z0LlNoYXJlUG9pbnQuV2ViQ29udHJvbHMuU1BDb250cm9sTW9kZSwgTWljcm9zb2Z0LlNoYXJlUG9pbnQsIFZlcnNpb249MTYuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49NzFlOWJjZTExMWU5NDI5YwFkAhcPZBYCAgMPZBYCZg9kFgJmDzwrAAYAZAIZD2QWAgIBD2QWAgUmZ18xNDU1Zjk2Ml9jMmM0XzQyZWNfOThkMF82N2EwZTY4YWY4ZTkPZBYEZg8WAh4HVmlzaWJsZWhkAgEPFgIfAWhkAgUPZBYCAgYPZBYCAgIPZBYCAgEPZBYCAgMPFgIfAWgWAmYPZBYEAgMPZBYEAgEPFgIfAWhkAgMPFgIfAWhkAgQPDxYCHglBY2Nlc3NLZXkFAS9kZGSaZRH2aTDLltNDQH3Cy5+Ff7A6OOWjYicXosYqkTRZRg==" />\r\n\r\n\r\n<script type="text/javascript">\r\n//<![CDATA[\r\nvar MSOWebPartPageFormName = \'aspnetForm\';\nvar g_presenceEnabled = true;\nvar g_wsaEnabled = false;\n\nvar g_correlationId = \'97f0b3a0-d9db-6077-d874-82596e99142a\';\nvar g_wsaQoSEnabled = false;\nvar g_wsaQoSDataPoints = [];\nvar g_wsaRUMEnabled = false;\nvar g_wsaLCID = 1033;\nvar g_wsaListTemplateId = 850;\nvar g_wsaSiteTemplateId = \'STS#0\';\nvar _fV4UI=true;var _spPageContextInfo = {webServerRelativeUrl: "\\u002f", webAbsoluteUrl: "https:\\u002f\\u002fwww.recenter.tamu.edu", siteAbsoluteUrl: "https:\\u002f\\u002fwww.recenter.tamu.edu", serverRequestPath: "\\u002fPages\\u002fhousing-activity.aspx", layoutsUrl: "_layouts\\u002f15", webTitle: "Real Estate Center", webTemplate: "1", tenantAppVersion: "0", isAppWeb: false, Has2019Era: true, webLogoUrl: "_layouts\\u002f15\\u002fimages\\u002fsiteicon.png", webLanguage: 1033, currentLanguage: 1033, currentUICultureName: "en-US", currentCultureName: "en-US", clientServerTimeDelta: new Date("2023-05-18T03:17:17.9170389Z") - new Date(), updateFormDigestPageLoaded: new Date("2023-05-18T03:17:17.9170389Z"), siteClientTag: "2906$$16.0.5056.1001", crossDomainPhotosEnabled:false, webUIVersion:15, webPermMasks:{High:16,Low:196673},pageListId:"{377a456c-c72a-435b-8851-384c6bfc543e}",pageItemId:13, pagePersonalizationScope:1, alertsEnabled:true, siteServerRelativeUrl: "\\u002f", allowSilverlightPrompt:\'True\', isSiteAdmin: false};document.onreadystatechange=fnRemoveAllStatus; function fnRemoveAllStatus(){removeAllStatus(true)};Flighting.ExpFeatures = [480215056,1880287568,1561350208,302071836,3212816,69472768,4194310,-2113396707,268502022,-872284160,1049232,-2147421952,65536,65536,2097472,917504,-2147474174,1372324107,67108882,0,0,-2147483648,2097152,0,0,32768,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32768];var _spWebPartComponents = new Object();//]]>\r\n</script>\r\n\r\n<script src="/_layouts/15/blank.js?rev=01HRKg2GvQ0OLPDOjRjeBw%3D%3DTAG0" type="text/javascript"></script>\r\n<script type="text/javascript">\r\n//<![CDATA[\r\nif (typeof(DeferWebFormInitCallback) == \'function\') DeferWebFormInitCallback();//]]>\r\n</script>\r\n\r\n<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="BF82A2A0" />\r\n        <!--removeIf(local)-->\r\n        <div id="ms-designer-ribbon">\r\n            \r\n            <div id="TurnOnAccessibility" style="display:none" class="s4-notdlg noindex">\r\n                <a id="linkTurnOnAcc" href="#" class="ms-accessible ms-acc-button" onclick="SetIsAccessibilityFeatureEnabled(true);UpdateAccessibilityUI();document.getElementById(\'linkTurnOffAcc\').focus();return false;">\r\n                    Turn on more accessible mode\r\n                </a>\r\n            </div>\r\n            <div id="TurnOffAccessibility" style="display:none" class="s4-notdlg noindex">\r\n                <a id="linkTurnOffAcc" href="#" class="ms-accessible ms-acc-button" onclick="SetIsAccessibilityFeatureEnabled(false);UpdateAccessibilityUI();document.getElementById(\'linkTurnOnAcc\').focus();return false;">\r\n                    Turn off more accessible mode\r\n                </a>\r\n            </div>\r\n            <div>\r\n\t\r\n\t<div id="s4-ribbonrow" style="visibility:hidden;display:none"></div>\r\n\r\n</div>\r\n\r\n\r\n            \r\n        </div>\r\n        <!--endRemoveIf(local)-->\r\n        <div id="s4-workspace" class="s4-nosetwidth">\r\n            <div id="s4-bodyContainer" ng-controller="MainCtrl" ng-cloak="">\r\n                <div ng-include="\'app/components/navbar/navbar.html\'"></div>\r\n                <div class="rec-banner">\r\n                    <a ng-href="{{banner.link}}">\r\n                        <img ng-src="{{banner.source}}" ng-if="banner.source" />\r\n                    </a>\r\n                </div>\r\n                <div class="container">\r\n                    <h1 ng-if="titleBar.title" class="page-header">{{titleBar.title}}</h1>\r\n                    <p ng-if="titleBar.tagline" class="tagline">{{titleBar.tagline}}</p>\r\n                    <div>\r\n                        \r\n                        \r\n                        <span id="DeltaPlaceHolderMain">\r\n                            \r\n            <div>\r\n                \r\n                \r\n                \r\n                \r\n                \r\n            </div>\r\n            <div class="row">\r\n                <div class="col-xs-12">\r\n                    <div data-name="WebPartZone">\r\n                        \r\n                        \r\n                        <div>\r\n                            <div class="ms-webpart-zone ms-fullWidth">\r\n\t<div id="MSOZoneCell_WebPartWPQ1" class="s4-wpcell-plain ms-webpartzone-cell ms-webpart-cell-vertical ms-fullWidth ">\r\n\t\t<div class="ms-webpart-chrome ms-webpart-chrome-vertical ms-webpart-chrome-fullWidth ">\r\n\t\t\t<div WebPartID="1455f962-c2c4-42ec-98d0-67a0e68af8e9" HasPers="false" id="WebPartWPQ1" width="100%" class="ms-WPBody noindex " allowDelete="false" style="" ><div class="ms-rtestate-field"><div class="row building-data data-page" ng-controller="HousingDataCtrl" ng-cloak="">\n    <update-meta name="description" content="Housing statistics are based on listing data from over 50 MLS (Multiple Listing Service) systems in Texas. Statistics for each geography were calculated based on listings of properties physically located within the mapped area presented with the statistics."></update-meta>\n    <div class="col-xs-12 col-sm-8" ng-if="!selected.view">\n        <div ng-if="oldDataIsAvailable && !oldData">\n            <h1>Housing Activity &amp; Affordability</h1>\n            <p>Residential home sales, listings, price activity and affordability for nearly 50 Texas metropolitan MLS (Multiple Listing Service) areas.</p>\n            <h4>About the Data</h4>\n            <p>\n                Data used in Housing Activity comes from the Texas REALTOR&reg; Data Relevance Project, a partnership among local REALTOR&reg; associations and their MLSs, the Texas Real Estate Research Center at Texas A&M University, and the Texas Association of REALTORS&reg;.\n                The Data Relevance Project data series differs from the Discontinued Housing Activity data series in two ways:\n            </p>\n            <ol>\n                <li>Includes data from more MLS systems in Texas.</li>\n                <li>A deduplication process has been implemented to remove duplicate listings for a single property.</li>\n            </ol>\n            <p>This process eliminates the impact of properties that have been listed multiple times within an MLS system or across multiple MLS systems.</p>\n        </div>\n        <div ng-if="oldDataIsAvailable && oldData">\n            <h3>Housing Activity &amp; Affordability (Discontinued)</h3>\n            <p>Residential home sales, listings, price activity and affordability for nearly 50 Texas metropolitan MLS (Multiple Listing Service) areas.</p>\n            <h4>About the Data</h4>\n            <p>\n                Data in this Discontinued series was independently reported to the Texas Real Estate Research Center by MLS systems across Texas. As of December 2015 this reporting process has been replaced by MLS system reporting through the Texas REALTOR\xc2\xae Data Relevance Project. The Center has retired this data series and will no longer make updates to it.\n            </p>\n        </div>\n        <div ng-if="!oldDataIsAvailable">\n            <h1>Housing Activity</h1>\n            <h4>Data Series Description</h4>\n            <p>\n                Housing statistics are based on listing data from over 50 MLS (Multiple Listing Service) systems in Texas. Statistics for each geography were calculated based on listings of properties physically located within the mapped area presented with the statistics.\n            </p>\n            <h4>Geographic Definitions</h4>\n            <p>\n                Metropolitan Statistical Area (MSA): Based on the multi-county area specified by The Office of Management & Budget in 2013.\n            </p>\n            <p>\n                Local Market Area (LMA): An area defined by the local Association/Board of REALTORS representing a logical market of homes that can be grouped together for meaningful statistical reporting.\n            </p>\n            <h4>Getting More Detail</h4>\n            <p>\n                For more detailed statistics about local areas, existing vs. new homes and breakout by property type, contact your local REALTOR&reg; association. <a href ="https://www.texasrealestate.com/about-us/local-associations/alphabetical-list/" target="_blank">Click here</a> for a list of contacts.\n            </p>\n            <h4>Data Release Dates</h4>\n            <p>\n                Statistics for geographies outside of the Houston metro area will be released on/near the 20th calendar day after month end. Statistics for the Houston metro area will be released on/near the 40th calendar day after month end.\n            </p>            \n        </div>\n    </div>\n    <div class="col-xs-12 col-sm-8" ng-show="data && selected.view == \'trends\'" ng-controller="HousingTrendsCtrl">\n        <h1>Housing Activity Trends</h1>\n        <update-title ng-if="selected.view == \'trends\'" title="Housing Activity Trends - Texas Real Estate Research Center"></update-title>\n        <tabset>\n            <tab ng-repeat="trend in trendTypes" heading="{{trend.name}}" select="selectTrendType(trend)">\n                \n            </tab>\n        </tabset>\n        <highchart config="trendChartConfig"></highchart>\n        <table class="table table-bordered table-hover table-condensed rec-table fix-chrome-copy-bug">\n            <thead>\n                <tr>\n                     <th rowspan="2">MLS Area</

In [6]:
soup = BeautifulSoup(response.content, 'html.parser')

In [7]:
soup.title

<title>



            Housing Activity














 -
                                                                                                                                                                                                Real Estate Center


</title>

In [8]:
soup.find('td', class_ = 'ng-binding')

In [9]:
soup.select('td', class_='ng-binding')

[<td>{{row.name}}</td>,
 <td>{{row[selected.trend.key].now | number}}</td>,
 <td>{{row[selected.trend.key].lastMonth | number}}</td>,
 <td>{{row[selected.trend.key].yearAgo | number}}</td>,
 <td>{{row[selected.trend.key].changeYOY | number : 1}}</td>,
 <td>{{row[selected.trend.key].totalYTD | number}}</td>,
 <td>{{row[selected.trend.key].changeYTD | number : 1}}</td>,
 <td><a ng-href="{{global.assetsUrl + row.mapImage}}" ng-if="row.mapImage" target="_blank">Link</a></td>,
 <td ng-if="selected.activityBucket.key != 'annualData'">{{row.date | date:'MMM yyyy':'UTC'}}</td>,
 <td ng-if="selected.activityBucket.key == 'annualData'">{{row.date | date:'yyyy':'UTC'}}</td>,
 <td>{{row.sales | number}}</td>,
 <td>{{row.volume | number}}</td>,
 <td>{{row.averagePrice | number}}</td>,
 <td>{{row.medianPrice | number}}</td>,
 <td>{{row.active | number}}</td>,
 <td>{{row.inventory | number : 1}}</td>,
 <td>{{row.priceRange}}</td>,
 <td ng-repeat="year in data[selected.activityBucket.key].years">{{row.years[year] | number : 1}}</td>]

In [10]:
monthly_sales = pd.read_csv('monthly_home_sales_sa.csv')
annual_sales = pd.read_csv('annual_home_sales_sa_metro.csv')
pct_distribution = pd.read_csv('pct_distribution_sa_metro.csv')

In [11]:
monthly_sales

,Date,Sales,Dollar\nVolume,Average\nPrice,Median\nPrice,Total\nListings,Months\nInventory
0,Jan 1990,478,"35,062,256","73,352","63,830","8,211",17.2
1,Feb 1990,363,"27,456,231","75,637","60,258","9,280",22.1
2,Mar 1990,553,"45,066,182","81,494","61,548","9,335",20.1
3,Apr 1990,429,"38,545,221","89,849","59,067","9,545",20.9
4,May 1990,537,"48,376,719","90,087","62,143","9,588",20.3
...,...,...,...,...,...,...,...
394,Nov 2022,"2,317","851,014,583","367,292","314,000","10,061",3.2
395,Dec 2022,"2,503","934,416,251","373,319","317,000","9,499",3.1
396,Jan 2023,"1,816","663,710,971","365,480","304,500","9,497",3.1
397,Feb 2023,"2,396","857,492,587","357,885","305,000","9,514",3.2
398,Mar 2023,"3,148","1,139,024,429","361,825","310,000","9,189",3.1

In [12]:
annual_sales

,Date,Sales,Dollar\nVolume,Average\nPrice,Median\nPrice,Total\nListings,Months\nInventory
0,1990,"6,322","495,787,279","78,423","62,479","8,877",15.2
1,1991,"6,431","517,302,399","80,439","63,815","6,875",10.8
2,1992,"6,895","587,653,358","85,229","70,146","6,009",9.7
3,1993,"7,450","708,074,856","95,044","75,390","5,367",8.0
4,1994,"7,375","714,696,790","96,908","76,707","5,357",8.6
5,1995,"7,117","709,136,187","99,640","79,928","6,132",10.6
6,1996,"10,872","1,111,251,572","102,212","83,915","7,519",7.9
7,1997,"11,388","1,214,310,541","106,631","86,340","7,955",7.9
8,1998,"13,563","1,486,011,628","109,564","87,794","7,301",5.5
9,1999,"15,275","1,722,030,704","112,735","89,454","6,393",4.6
10,2000,"15,802","1,894,608,547","119,897","93,787","6,446",4.8
11,2001,"16,497","2,055,003,631","124,568","99,649","6,859",4.6
12,2002,"16,204","2,131,267,982","131,527","106,801","7,117",5.2
13,2003,"18,149","2,512,012,665","138,411","113,870","8,066",5.2
14,2004,"20,869","3,007,498,486","144,113","119,292","8,796",5.0
15,2005,"24,530","3,836,066,259","156,383","131,019","8,490",3.7
16,2006,"26,736","4,529,582,939","169,419","140,361","8,695",4.1
17,2007,"24,450","4,403,003,416","180,082","147,829","12,026",5.8
18,2008,"19,709","3,585,516,801","181,923","148,231","13,360",7.5
19,2009,"19,040","3,400,278,882","178,586","147,776","12,253",7.1
20,2010,"18,755","3,442,695,240","183,561","149,951","12,785",7.5
21,2011,"18,794","3,453,129,674","183,736","151,000","11,944",6.5
22,2012,"20,838","4,017,440,149","192,794","159,000","10,412",5.1
23,2013,"24,444","5,044,806,739","206,382","169,000","9,200",3.9
24,2014,"26,025","5,616,315,277","215,805","179,000","8,971",3.5
25,2015,"28,638","6,568,895,963","229,377","190,000","8,452",3.3
26,2016,"30,945","7,332,874,845","236,965","201,900","8,705",2.9
27,2017,"32,027","7,890,412,989","246,368","210,000","8,808",2.9
28,2018,"33,263","8,541,894,260","256,799","221,292","9,070",3.1
29,2019,"35,547","9,502,613,310","267,325","230,000","9,981",3.1
30,2020,"39,549","11,467,599,272","289,959","248,046","7,852",1.7
31,2021,"41,622","13,962,923,054","335,470","283,000","5,037",1.4
32,2022,"37,123","13,915,480,938","374,848","320,000","7,094",3.1

In [13]:
pct_distribution

,Price Range,Percent Distribution,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
1,"$0 - $69,999",13.3,12.1,8.9,6.6,4.8,3.8,2.6,1.9,1.6,0.9,0.4,0.4
2,"$70,000 - $99,999",11.3,10.5,9.5,8.2,6.6,5.3,4.1,3.6,2.8,1.8,1.2,0.9
3,"$100,000 - $149,999",24.6,23.2,22.2,20.4,18.3,15.5,13.8,11.3,9.4,6.6,4.2,3.2
4,"$150,000 - $199,999",20.1,19.8,21.3,23.3,23.9,24.5,25.0,23.4,21.4,17.5,10.5,6.5
5,"$200,000 - $249,999",10.6,11.6,12.6,13.6,15.2,17.3,18.7,20.7,22.9,23.9,19.2,11.9
6,"$250,000 - $299,999",6.9,7.5,8.6,9.5,10.5,11.6,12.2,13.5,14.5,16.9,20.2,19.1
7,"$300,000 - $399,999",7.4,8.8,9.1,10.2,11.5,12.0,12.8,14.2,15.0,16.6,21.6,28.2
8,"$400,000 - $499,999",2.6,3.2,3.9,4.1,4.9,5.4,5.8,6.1,6.6,7.8,10.2,12.9
9,"$500,000 - $749,999",2.3,2.3,2.7,3.0,3.3,3.4,3.6,3.9,4.4,5.8,8.8,11.9
10,"$750,000 - $999,999",0.5,0.6,0.8,0.7,0.8,0.7,0.8,0.8,1.0,1.3,2.2,3.1
11,"$1,000,000",0.4,0.4,0.4,0.4,0.5,0.5,0.5,0.6,0.6,0.9,1.5,2.0

In [14]:
pct_distribution.columns = pct_distribution.loc[0]

In [15]:
pct_distribution.columns = pct_distribution.columns.astype('str')

In [16]:
pct_distribution.rename(columns=lambda x: x.split(".")[0], inplace=True)

In [17]:
pct_distribution= pct_distribution[1:]

In [18]:
pct_distribution.set_index('nan', inplace=True)

In [19]:
new_index = pct_distribution.index.tolist()
new_index

['$0 - $69,999',
 '$70,000 - $99,999',
 '$100,000 - $149,999',
 '$150,000 - $199,999',
 '$200,000 - $249,999',
 '$250,000 - $299,999',
 '$300,000 - $399,999',
 '$400,000 - $499,999',
 '$500,000 - $749,999',
 '$750,000 - $999,999',
 '$1,000,000']

In [20]:
last_index_value = pct_distribution.index[-1].split('$')[1]
new_index[-1] = last_index_value
pct_distribution.index = new_index

In [21]:
pct_distribution.rename_axis('price_range', inplace=True)

In [22]:
pct_distribution

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
price_range,,,,,,,,,,,,
"$0 - $69,999",13.3,12.1,8.9,6.6,4.8,3.8,2.6,1.9,1.6,0.9,0.4,0.4
"$70,000 - $99,999",11.3,10.5,9.5,8.2,6.6,5.3,4.1,3.6,2.8,1.8,1.2,0.9
"$100,000 - $149,999",24.6,23.2,22.2,20.4,18.3,15.5,13.8,11.3,9.4,6.6,4.2,3.2
"$150,000 - $199,999",20.1,19.8,21.3,23.3,23.9,24.5,25.0,23.4,21.4,17.5,10.5,6.5
"$200,000 - $249,999",10.6,11.6,12.6,13.6,15.2,17.3,18.7,20.7,22.9,23.9,19.2,11.9
"$250,000 - $299,999",6.9,7.5,8.6,9.5,10.5,11.6,12.2,13.5,14.5,16.9,20.2,19.1
"$300,000 - $399,999",7.4,8.8,9.1,10.2,11.5,12.0,12.8,14.2,15.0,16.6,21.6,28.2
"$400,000 - $499,999",2.6,3.2,3.9,4.1,4.9,5.4,5.8,6.1,6.6,7.8,10.2,12.9
"$500,000 - $749,999",2.3,2.3,2.7,3.0,3.3,3.4,3.6,3.9,4.4,5.8,8.8,11.9
"$750,000 - $999,999",0.5,0.6,0.8,0.7,0.8,0.7,0.8,0.8,1.0,1.3,2.2,3.1
"1,000,000",0.4,0.4,0.4,0.4,0.5,0.5,0.5,0.6,0.6,0.9,1.5,2.0

In [23]:
monthly_sales = monthly_sales.rename(columns={'Date':'date', 'Sales':'sales', 'Dollar\nVolume':'dollar_volume',
                                             'Average\nPrice':'average_price', 'Median\nPrice': 'median_price',
                                             'Total\nListings':'total_listings', 'Months\nInventory':'months_inventory'})

In [24]:
monthly_sales

,date,sales,dollar_volume,average_price,median_price,total_listings,months_inventory
0,Jan 1990,478,"35,062,256","73,352","63,830","8,211",17.2
1,Feb 1990,363,"27,456,231","75,637","60,258","9,280",22.1
2,Mar 1990,553,"45,066,182","81,494","61,548","9,335",20.1
3,Apr 1990,429,"38,545,221","89,849","59,067","9,545",20.9
4,May 1990,537,"48,376,719","90,087","62,143","9,588",20.3
...,...,...,...,...,...,...,...
394,Nov 2022,"2,317","851,014,583","367,292","314,000","10,061",3.2
395,Dec 2022,"2,503","934,416,251","373,319","317,000","9,499",3.1
396,Jan 2023,"1,816","663,710,971","365,480","304,500","9,497",3.1
397,Feb 2023,"2,396","857,492,587","357,885","305,000","9,514",3.2
398,Mar 2023,"3,148","1,139,024,429","361,825","310,000","9,189",3.1

In [25]:
annual_sales.rename(columns={'Date':'date', 'Sales':'sales', 'Dollar\nVolume':'dollar_volume',
                             'Average\nPrice':'average_price', 'Median\nPrice': 'median_price',
                             'Total\nListings':'total_listings', 'Months\nInventory':'months_inventory'},
                   inplace=True)

In [26]:
annual_sales

,date,sales,dollar_volume,average_price,median_price,total_listings,months_inventory
0,1990,"6,322","495,787,279","78,423","62,479","8,877",15.2
1,1991,"6,431","517,302,399","80,439","63,815","6,875",10.8
2,1992,"6,895","587,653,358","85,229","70,146","6,009",9.7
3,1993,"7,450","708,074,856","95,044","75,390","5,367",8.0
4,1994,"7,375","714,696,790","96,908","76,707","5,357",8.6
5,1995,"7,117","709,136,187","99,640","79,928","6,132",10.6
6,1996,"10,872","1,111,251,572","102,212","83,915","7,519",7.9
7,1997,"11,388","1,214,310,541","106,631","86,340","7,955",7.9
8,1998,"13,563","1,486,011,628","109,564","87,794","7,301",5.5
9,1999,"15,275","1,722,030,704","112,735","89,454","6,393",4.6
10,2000,"15,802","1,894,608,547","119,897","93,787","6,446",4.8
11,2001,"16,497","2,055,003,631","124,568","99,649","6,859",4.6
12,2002,"16,204","2,131,267,982","131,527","106,801","7,117",5.2
13,2003,"18,149","2,512,012,665","138,411","113,870","8,066",5.2
14,2004,"20,869","3,007,498,486","144,113","119,292","8,796",5.0
15,2005,"24,530","3,836,066,259","156,383","131,019","8,490",3.7
16,2006,"26,736","4,529,582,939","169,419","140,361","8,695",4.1
17,2007,"24,450","4,403,003,416","180,082","147,829","12,026",5.8
18,2008,"19,709","3,585,516,801","181,923","148,231","13,360",7.5
19,2009,"19,040","3,400,278,882","178,586","147,776","12,253",7.1
20,2010,"18,755","3,442,695,240","183,561","149,951","12,785",7.5
21,2011,"18,794","3,453,129,674","183,736","151,000","11,944",6.5
22,2012,"20,838","4,017,440,149","192,794","159,000","10,412",5.1
23,2013,"24,444","5,044,806,739","206,382","169,000","9,200",3.9
24,2014,"26,025","5,616,315,277","215,805","179,000","8,971",3.5
25,2015,"28,638","6,568,895,963","229,377","190,000","8,452",3.3
26,2016,"30,945","7,332,874,845","236,965","201,900","8,705",2.9
27,2017,"32,027","7,890,412,989","246,368","210,000","8,808",2.9
28,2018,"33,263","8,541,894,260","256,799","221,292","9,070",3.1
29,2019,"35,547","9,502,613,310","267,325","230,000","9,981",3.1
30,2020,"39,549","11,467,599,272","289,959","248,046","7,852",1.7
31,2021,"41,622","13,962,923,054","335,470","283,000","5,037",1.4
32,2022,"37,123","13,915,480,938","374,848","320,000","7,094",3.1

In [27]:
annual_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              33 non-null     int64
 1   sales             33 non-null     object
 2   dollar_volume     33 non-null     object
 3   average_price     33 non-null     object
 4   median_price      33 non-null     object
 5   total_listings    33 non-null     object
 6   months_inventory  33 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 1.9+ KB

In [28]:
annual_sales['sales'].str.replace(',','')

0      6322
1      6431
2      6895
3      7450
4      7375
5      7117
6     10872
7     11388
8     13563
9     15275
10    15802
11    16497
12    16204
13    18149
14    20869
15    24530
16    26736
17    24450
18    19709
19    19040
20    18755
21    18794
22    20838
23    24444
24    26025
25    28638
26    30945
27    32027
28    33263
29    35547
30    39549
31    41622
32    37123
Name: sales, dtype: object

In [29]:
def percent_distribution(csv):
    pct_distribution = pd.read_csv(csv)
    
    pct_distribution.columns = pct_distribution.iloc[0]
    pct_distribution.columns = pct_distribution.columns.astype('str')
    pct_distribution.rename(columns=lambda x: x.split(".")[0], inplace=True)
    pct_distribution = pct_distribution[1:]
    
    
    pct_distribution = pct_distribution.rename(columns={pct_distribution.columns[0]: 'price_range'})
    pct_distribution = pct_distribution.set_index('price_range')
    
    new_index = pct_distribution.index.tolist()
    last_index_value = pct_distribution.index[-1].split('$')[1]
    new_index[-1] = last_index_value
    pct_distribution.index = new_index
    
    pct_distribution.rename_axis('price_range', inplace=True)
    
    return pct_distribution

In [30]:
pct_distribution_sa = percent_distribution('pct_distribution_sa_metro.csv')
pct_distribution_sa

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
price_range,,,,,,,,,,,,
"$0 - $69,999",13.3,12.1,8.9,6.6,4.8,3.8,2.6,1.9,1.6,0.9,0.4,0.4
"$70,000 - $99,999",11.3,10.5,9.5,8.2,6.6,5.3,4.1,3.6,2.8,1.8,1.2,0.9
"$100,000 - $149,999",24.6,23.2,22.2,20.4,18.3,15.5,13.8,11.3,9.4,6.6,4.2,3.2
"$150,000 - $199,999",20.1,19.8,21.3,23.3,23.9,24.5,25.0,23.4,21.4,17.5,10.5,6.5
"$200,000 - $249,999",10.6,11.6,12.6,13.6,15.2,17.3,18.7,20.7,22.9,23.9,19.2,11.9
"$250,000 - $299,999",6.9,7.5,8.6,9.5,10.5,11.6,12.2,13.5,14.5,16.9,20.2,19.1
"$300,000 - $399,999",7.4,8.8,9.1,10.2,11.5,12.0,12.8,14.2,15.0,16.6,21.6,28.2
"$400,000 - $499,999",2.6,3.2,3.9,4.1,4.9,5.4,5.8,6.1,6.6,7.8,10.2,12.9
"$500,000 - $749,999",2.3,2.3,2.7,3.0,3.3,3.4,3.6,3.9,4.4,5.8,8.8,11.9
"$750,000 - $999,999",0.5,0.6,0.8,0.7,0.8,0.7,0.8,0.8,1.0,1.3,2.2,3.1
"1,000,000",0.4,0.4,0.4,0.4,0.5,0.5,0.5,0.6,0.6,0.9,1.5,2.0

In [50]:
def monthly_sales(csv):
    
    monthly_sales = pd.read_csv(csv)
    
    monthly_sales =  monthly_sales.rename(columns={'Date':'date', 'Sales':'sales', 'Dollar\nVolume':'dollar_volume',
                                             'Average\nPrice':'average_price', 'Median\nPrice': 'median_price',
                                             'Total\nListings':'total_listings', 'Months\nInventory':'months_inventory'})
    
    columns = ['sales', 'dollar_volume', 'average_price', 'median_price', 'total_listings']
    for col in columns:
        monthly_sales[col] = monthly_sales[col].str.replace(',','')
    
    for col in columns:
        monthly_sales[col] = monthly_sales[col].astype(float)
    
    monthly_sales['date']=pd.to_datetime(monthly_sales['date'])
    
    pd.options.display.float_format = '{:.1f}'.format
    
    return monthly_sales

In [51]:
#pd.options.display.float_format = '{:.1f}'.format
monthly_sales_sa = monthly_sales('monthly_home_sales_sa.csv')
monthly_sales_sa

,date,sales,dollar_volume,average_price,median_price,total_listings,months_inventory
0,1990-01-01,478.0,35062256.0,73352.0,63830.0,8211.0,17.2
1,1990-02-01,363.0,27456231.0,75637.0,60258.0,9280.0,22.1
2,1990-03-01,553.0,45066182.0,81494.0,61548.0,9335.0,20.1
3,1990-04-01,429.0,38545221.0,89849.0,59067.0,9545.0,20.9
4,1990-05-01,537.0,48376719.0,90087.0,62143.0,9588.0,20.3
...,...,...,...,...,...,...,...
394,2022-11-01,2317.0,851014583.0,367292.0,314000.0,10061.0,3.2
395,2022-12-01,2503.0,934416251.0,373319.0,317000.0,9499.0,3.1
396,2023-01-01,1816.0,663710971.0,365480.0,304500.0,9497.0,3.1
397,2023-02-01,2396.0,857492587.0,357885.0,305000.0,9514.0,3.2
398,2023-03-01,3148.0,1139024429.0,361825.0,310000.0,9189.0,3.1

In [33]:
monthly_sales_sa['date']=pd.to_datetime(monthly_sales_sa['date'])

In [34]:
monthly_sales_sa.columns.tolist()

['date',
 'sales',
 'dollar_volume',
 'average_price',
 'median_price',
 'total_listings',
 'months_inventory']

In [36]:
columns = ['sales', 'dollar_volume', 'average_price', 'median_price', 'total_listings']
for col in columns:
    monthly_sales_sa[col] = monthly_sales_sa[col].str.replace(',','')
    
monthly_sales_sa

AttributeError: Can only use .str accessor with string values!

In [37]:
for col in columns:
    
    monthly_sales_sa[col] = monthly_sales_sa[col].astype(float)
    
monthly_sales_sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              399 non-null    datetime64[ns]
 1   sales             399 non-null    float64
 2   dollar_volume     399 non-null    float64
 3   average_price     399 non-null    float64
 4   median_price      399 non-null    float64
 5   total_listings    399 non-null    float64
 6   months_inventory  399 non-null    object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 21.9+ KB

In [38]:
monthly_sales_sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              399 non-null    datetime64[ns]
 1   sales             399 non-null    float64
 2   dollar_volume     399 non-null    float64
 3   average_price     399 non-null    float64
 4   median_price      399 non-null    float64
 5   total_listings    399 non-null    float64
 6   months_inventory  399 non-null    object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 21.9+ KB

In [39]:
monthly_sales_sa

,date,sales,dollar_volume,average_price,median_price,total_listings,months_inventory
0,1990-01-01,478.0,3.506226e+07,73352.0,63830.0,8211.0,17.2
1,1990-02-01,363.0,2.745623e+07,75637.0,60258.0,9280.0,22.1
2,1990-03-01,553.0,4.506618e+07,81494.0,61548.0,9335.0,20.1
3,1990-04-01,429.0,3.854522e+07,89849.0,59067.0,9545.0,20.9
4,1990-05-01,537.0,4.837672e+07,90087.0,62143.0,9588.0,20.3
...,...,...,...,...,...,...,...
394,2022-11-01,2317.0,8.510146e+08,367292.0,314000.0,10061.0,3.2
395,2022-12-01,2503.0,9.344163e+08,373319.0,317000.0,9499.0,3.1
396,2023-01-01,1816.0,6.637110e+08,365480.0,304500.0,9497.0,3.1
397,2023-02-01,2396.0,8.574926e+08,357885.0,305000.0,9514.0,3.2
398,2023-03-01,3148.0,1.139024e+09,361825.0,310000.0,9189.0,3.1